/* psat_provenance.js  —  FOR 30daypsatplan.com (the PSAT site) ONLY
   Self-contained. Does two things on the landing page:
     1. Adds a "Who wrote all the questions for this website?" button under the
        hero headline, opening a full-page overlay in Dr. Brink's voice.
     2. Replaces the tagline "The plan is already written. You just have to open it."
        with "Your personalized PSAT prep plan. Start today".
     3. Adds a card just above the footer with a plain link to /psat-math-skills/
        (a real <a href>, so Google and Bing can follow it from the homepage).
   No existing markup, checkout, or enroll code is touched.

   Load this AFTER the page's own scripts, just before </body> in the ROOT
   index.html of the dasbrink/30dayPSATplan repo:
     <script src="psat_provenance.js"></script>
*/
(function () {
  "use strict";

  // PSAT design system
  var OXBLOOD = "#A32B3F";
  var INK     = "#241C22";
  var CARD    = "#F7F2E7";
  var OAT     = "#EDE6D6";
  var DISPLAY = "'Zilla Slab', Georgia, serif";
  var BODY    = "'Karla', system-ui, -apple-system, Arial, sans-serif";

  // ---- Overlay (hidden until the button is clicked) --------------------------
  function buildOverlay() {
    if (document.getElementById("psatProvOverlay")) return;

    var overlay = document.createElement("div");
    overlay.id = "psatProvOverlay";
    overlay.setAttribute("role", "dialog");
    overlay.setAttribute("aria-modal", "true");
    overlay.setAttribute("aria-label", "Who wrote these questions");
    overlay.style.cssText = [
      "position:fixed",
      "inset:0",
      "z-index:2147483000",
      "display:none",
      "background:rgba(36,28,34,0.78)",
      "overflow-y:auto",
      "-webkit-overflow-scrolling:touch",
      "padding:24px"
    ].join(";");

    var card = document.createElement("div");
    card.style.cssText = [
      "max-width:640px",
      "margin:48px auto",
      "background:" + CARD,
      "border-top:6px solid " + OXBLOOD,
      "border-radius:10px",
      "box-shadow:0 20px 60px rgba(0,0,0,0.40)",
      "padding:36px 32px 32px 32px",
      "font-family:" + BODY,
      "color:" + INK,
      "line-height:1.6",
      "position:relative"
    ].join(";");

    // Close (X)
    var close = document.createElement("button");
    close.type = "button";
    close.setAttribute("aria-label", "Close");
    close.innerHTML = "&times;";
    close.style.cssText = [
      "position:absolute",
      "top:10px",
      "right:14px",
      "background:none",
      "border:none",
      "font-size:30px",
      "line-height:1",
      "color:" + OXBLOOD,
      "cursor:pointer",
      "font-family:" + DISPLAY
    ].join(";");
    close.addEventListener("click", hideOverlay);

    var h = document.createElement("h2");
    h.style.cssText = "margin:0 0 18px 0;font-size:24px;color:" + INK + ";font-family:" + DISPLAY + ";";
    h.textContent = "Every question in this plan was written by me, one at a time.";

    var p1 = document.createElement("p");
    p1.style.cssText = "margin:0 0 16px 0;";
    p1.textContent = "Not generated by a machine, not scraped off the internet. I wrote them, as a teacher, for real students.";

    var p2 = document.createElement("p");
    p2.style.cssText = "margin:0 0 16px 0;";
    p2.textContent = "Thirty-two years in a math classroom teaches you where students actually go wrong, and why. That is what went into every question and every explanation here.";

    var p3 = document.createElement("p");
    p3.style.cssText = "margin:0 0 16px 0;";
    p3.textContent = "A machine can produce a thousand questions in a minute. It cannot tell you why a student got one wrong, or what to do about it. That difference is the whole point of this plan.";

    var sig = document.createElement("p");
    sig.style.cssText = "margin:24px 0 0 0;font-style:italic;color:" + OXBLOOD + ";font-family:" + DISPLAY + ";";
    sig.textContent = "Dr. Brink";

    var done = document.createElement("button");
    done.type = "button";
    done.textContent = "Close";
    done.style.cssText = "margin-top:26px;background:" + OXBLOOD + ";color:" + CARD + ";border:none;border-radius:6px;padding:12px 26px;font-size:16px;font-family:" + DISPLAY + ";cursor:pointer;";
    done.addEventListener("click", hideOverlay);

    card.appendChild(close);
    card.appendChild(h);
    card.appendChild(p1);
    card.appendChild(p2);
    card.appendChild(p3);
    card.appendChild(sig);
    card.appendChild(done);
    overlay.appendChild(card);
    overlay.addEventListener("click", function (e) { if (e.target === overlay) hideOverlay(); });
    document.body.appendChild(overlay);
  }

  function showOverlay() {
    buildOverlay();
    var o = document.getElementById("psatProvOverlay");
    if (o) o.style.display = "block";
    document.addEventListener("keydown", escToClose);
  }
  function hideOverlay() {
    var o = document.getElementById("psatProvOverlay");
    if (o) o.style.display = "none";
    document.removeEventListener("keydown", escToClose);
  }
  function escToClose(e) { if (e.key === "Escape" || e.keyCode === 27) hideOverlay(); }

  // ---- The button ------------------------------------------------------------
  function makeButton() {
    var wrap = document.createElement("div");
    wrap.id = "psatProvWrap";
    wrap.style.cssText = "text-align:center;margin:22px auto 8px auto;";

    var btn = document.createElement("button");
    btn.id = "psatProvBtn";
    btn.type = "button";
    btn.textContent = "Who wrote all the questions for this website?";
    btn.style.cssText = [
      "display:inline-block",
      "background:" + OXBLOOD,
      "color:" + CARD,
      "border:none",
      "border-radius:8px",
      "padding:13px 26px",
      "font-size:17px",
      "font-weight:700",
      "font-family:" + DISPLAY,
      "cursor:pointer",
      "box-shadow:0 3px 10px rgba(163,43,63,0.30)"
    ].join(";");
    btn.addEventListener("click", showOverlay);
    btn.addEventListener("mouseenter", function () { btn.style.filter = "brightness(0.92)"; });
    btn.addEventListener("mouseleave", function () { btn.style.filter = "none"; });

    wrap.appendChild(btn);
    return wrap;
  }

  // ---- Insert the button just under the hero headline ------------------------
  function insertButton() {
    if (document.getElementById("psatProvWrap")) return;

    var anchor = document.querySelector("h1") || document.querySelector("h2");
    var wrap = makeButton();

    if (anchor && anchor.parentNode) {
      if (anchor.nextSibling) {
        anchor.parentNode.insertBefore(wrap, anchor.nextSibling);
      } else {
        anchor.parentNode.appendChild(wrap);
      }
    } else if (document.body) {
      document.body.insertBefore(wrap, document.body.firstChild);
    }
  }

  // ---- Swap the tagline ------------------------------------------------------
  // Handles the phrase whether it sits in one text node or is split across two
  // (e.g. two sentences on separate lines).
  function replaceTagline() {
    var replacements = [
      ["The plan is already written. You just have to open it.", "Your personalized PSAT prep plan. Start today"],
      ["The plan is already written.", "Your personalized PSAT prep plan."],
      ["You just have to open it.", "Start today"]
    ];

    var walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, null, false);
    var node;
    var nodes = [];
    while ((node = walker.nextNode())) { nodes.push(node); }

    nodes.forEach(function (n) {
      var t = n.nodeValue;
      if (!t) return;
      for (var i = 0; i < replacements.length; i++) {
        if (t.indexOf(replacements[i][0]) !== -1) {
          t = t.split(replacements[i][0]).join(replacements[i][1]);
        }
      }
      if (t !== n.nodeValue) { n.nodeValue = t; }
    });
  }

  // ---- Link card to the free skills page, just above the footer ---------------
  function insertSkillsLink() {
    if (document.getElementById("psatSkillsLink")) return;

    var sec = document.createElement("section");
    sec.id = "psatSkillsLink";
    sec.style.cssText = "padding:56px 0;";

    var wrap = document.createElement("div");
    wrap.className = "wrap";

    var card = document.createElement("div");
    card.style.cssText = [
      "background:" + CARD,
      "border:2px solid " + INK,
      "box-shadow:8px 8px 0 " + INK,
      "padding:28px 28px 30px",
      "max-width:760px",
      "font-family:" + BODY,
      "color:" + INK,
      "line-height:1.6"
    ].join(";");

    var tag = document.createElement("p");
    tag.style.cssText = "margin:0 0 8px 0;font-family:'Space Mono',monospace;font-size:12px;letter-spacing:.1em;text-transform:uppercase;color:" + OXBLOOD + ";";
    tag.textContent = "Free to read";

    var h = document.createElement("h3");
    h.style.cssText = "margin:0 0 12px 0;font-family:" + DISPLAY + ";font-size:26px;line-height:1.2;color:" + INK + ";";
    h.textContent = "Every skill the PSAT math section tests";

    var p = document.createElement("p");
    p.style.cssText = "margin:0 0 20px 0;";
    p.textContent = "All 280 skills behind the PSAT math questions, grouped from Grade 5 up, with the four content areas and how they are weighted. Most of them are what you are learning in 9th and 10th grade right now.";

    var a = document.createElement("a");
    a.href = "/psat-math-skills/";
    a.textContent = "See the PSAT math skills";
    a.style.cssText = "display:inline-block;background:" + OXBLOOD + ";color:" + CARD + ";text-decoration:none;border-radius:6px;padding:12px 24px;font-size:16px;font-weight:700;font-family:" + DISPLAY + ";";

    card.appendChild(tag);
    card.appendChild(h);
    card.appendChild(p);
    card.appendChild(a);
    wrap.appendChild(card);
    sec.appendChild(wrap);

    var footer = document.querySelector("footer");
    if (footer && footer.parentNode) {
      footer.parentNode.insertBefore(sec, footer);
    } else if (document.body) {
      document.body.appendChild(sec);
    }
  }

  function run() {
    insertButton();
    replaceTagline();
    insertSkillsLink();
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", run);
  } else {
    run();
  }
})();
